name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 72.56.66.228
          username: root
          key: ${{ secrets.CF_GSR_DEPLOY_KEY }}
          script: |
            set -e
            echo "🚀 Starting deployment at $(date)"
            
            # Запускаем деплой-скрипт
            /usr/local/bin/cf_gsr_deploy
            
            # Проверка статуса
            systemctl status --no-pager cf-gsr || true
            
            echo "✅ Deployment completed at $(date)"

